### ISSUE TITLE
gpu parallel running error

### ISSUE THREAD

**Issue by jasonxauat** [Kartik2605/GPU-Parallelised-Classical-LBM-ans-evaluation-2D-Lid-Driven-cavity-test.#1]
I'm in ubuntu22, installed nvidia hpc sdk, some simple openacc example test is ok, but this gpu paralled code "LBM_2D_parallel.cpp" was not runned:

`$ nvc++ -acc -gpu=cuda11.8 -o parallel LBM_2D_parallel.cpp`
`$ ./parallel `
`Failing in Thread:1`
`Accelerator Fatal Error: call to cuStreamSynchronize returned error 700 (CUDA_ERROR_ILLEGAL_ADDRESS): Illegal address during kernel execution`
` File: /home/jason/code/GPU-Parallelised-Classical-LBM-and-evaluation-on-2D-Lid-Driven-cavity-test.-main/LBM_2D_parallel.cpp`
` Function: main:88`
` Line: 113`

my gpu is GTX 1060 6G, I have other workstation with Tesla P100, but have not tried. Please give me some advice, thank you!

**Comment by Kartik2605** [comment]
Hey hi, 
Try using  -gpu=managed flag.
$ nvc++ -acc -gpu=managed -Minfo=accel -o parallel LBM_2D_parallel.cpp
$ ./parallel
To enable Unified Memory model, which simplifies memory management when programming for GPU.

**Comment by jasonxauat** [comment]
It works now, thanks. 
My GPU is 16.9 times faster than the CPU. P100 is probably much faster.
Also, is there any good learning document or tutorial for openacc? I see a lot of information online that is 10 years old.

**Comment by Kartik2605** [comment]
Great! 
I learned during my grad course on parallel computing. But there's NVIDIA developers free course on OpenACC. I found it helpful at the start.
